CREATE TABLE ITEMS(ITEMID INT PRIMARY KEY, ITEMNAME VARCHAR(50), CATEGORY VARCHAR(50), PRICE INT, INSTOCK INT CHECK(INSTOCK >=0));
CREATE TABLE CUSTOMERS(CUSTID INT PRIMARY KEY, CUSTNAME VARCHAR(50), ADDRESS VARCHAR(100), STATE VARCHAR(50));
CREATE TABLE ORDERS(ORDERID INT PRIMARY KEY, ITEMID INT, CUSTID INT, QUANTITY INT, ORDERDATE DATE, FOREIGN KEY(ITEMID) REFERENCES ITEMS(ITEMID), FOREIGN KEY(CUSTID) REFERENCES CUSTOMERS(CUSTID));
CREATE TABLE DELIVERY(DELIVERYID INT PRIMARY KEY, CUSTID INT, ORDERID INT, FOREIGN KEY(CUSTID) REFERENCES CUSTOMERS(CUSTID), FOREIGN KEY(ORDERID) REFERENCES ORDERS(ORDERID));

describe ITEMS;
describe CUSTOMERS;
describe ORDERS;
describe DELIVERY;

TRUNCATE TABLE ITEMS;
TRUNCATE TABLE CUSTOMERS;
TRUNCATE TABLE ORDERS;
TRUNCATE TABLE DELIVERY;

DROP TABLE ITEMS;
DROP TABLE CUSTOMERS;
DROP TABLE ORDERS;
DROP TABLE DELIVERY;

INSERT INTO ITEMS VALUES (1,'Samsung Galaxy S4','Mobile',6000,10);
INSERT INTO ITEMS VALUES (2,'iPhone 13','Mobile',8000,5);
INSERT INTO ITEMS VALUES (3,'Dell Laptop','Laptop',7000,7);
INSERT INTO ITEMS VALUES (4,'HP Laptop','Laptop',6500,8);
INSERT INTO ITEMS VALUES (5,'Sony Headphones','Accessories',2000,20);
SELECT * FROM ITEMS;

INSERT INTO CUSTOMERS VALUES (1,'Jade','New York','NY');
INSERT INTO CUSTOMERS VALUES (2,'Jack','California','CA');
INSERT INTO CUSTOMERS VALUES (3,'Mickey','Florida','FL');
INSERT INTO CUSTOMERS VALUES (4,'Jenny','Texas','TX');
INSERT INTO CUSTOMERS VALUES (5,'Meadows','Chicago','IL');
SELECT * FROM CUSTOMERS;

INSERT INTO ORDERS VALUES (101,1,1,1,'10-JAN-2014');
INSERT INTO ORDERS VALUES (102,3,2,1,'12-MAY-2012');
INSERT INTO ORDERS VALUES (103,2,3,2,'15-MARCH-2015');
INSERT INTO ORDERS VALUES (104,5,4,1,'21-JULY-2014');
INSERT INTO ORDERS VALUES (105,4,3,1,'10-SEPTEMBER-2013');
SELECT * FROM ORDERS;

INSERT INTO DELIVERY VALUES (1,1,101);
INSERT INTO DELIVERY VALUES (2,3,103);
INSERT INTO DELIVERY VALUES (3,4,104);
SELECT * FROM DELIVERY;

SELECT DISTINCT c.* FROM CUSTOMERS c JOIN ORDERS o ON c.CUSTID = o.CUSTID;
SELECT DISTINCT c.* FROM CUSTOMERS c JOIN ORDERS o ON c.CUSTID = o.CUSTID JOIN DELIVERY d ON o.CUSTID = d.CUSTID;
SELECT o.ORDERDATE FROM ORDERS o JOIN CUSTOMERS c ON o.CUSTID = c.CUSTID WHERE c.CUSTNAME LIKE 'J%';
SELECT i.ITEMNAME, i.PRICE FROM ITEMS i JOIN ORDERS o ON i.ITEMID = o.ITEMID JOIN CUSTOMERS c ON o.CUSTID = c.CUSTID WHERE c.CUSTNAME='Mickey';
SELECT DISTINCT c.* FROM CUSTOMERS c JOIN ORDERS o ON c.CUSTID = o.CUSTID WHERE o.ORDERDATE > '01-JAN-2013' AND o.orderid NOT IN (SELECT orderid FROM Delivery);
SELECT ITEMID FROM ORDERS UNION SELECT ITEMID FROM ORDERS WHERE ORDERID NOT IN (SELECT ORDERID FROM DELIVERY);
SELECT CUSTNAME FROM CUSTOMERS WHERE CUSTID IN (SELECT CUSTID FROM ORDERS)INTERSECT SELECT CUSTNAME FROM CUSTOMERS WHERE CUSTID IN (SELECT O.CUSTID FROM ORDERS O JOIN DELIVERY D ON O.ORDERID = D.ORDERID);
SELECT CUSTNAME FROM CUSTOMERS WHERE CUSTID IN (SELECT CUSTID FROM ORDERS) MINUS SELECT CUSTNAME FROM CUSTOMERS WHERE CUSTID IN (SELECT O.CUSTID FROM ORDERS O JOIN DELIVERY D ON O.ORDERID = D.ORDERID);
SELECT CUSTNAME FROM CUSTOMERS WHERE CUSTID = (SELECT CUSTID FROM ORDERS GROUP BY CUSTID HAVING COUNT(*) = (SELECT MAX(COUNT(*)) FROM ORDERS GROUP BY CUSTID));
SELECT DISTINCT C.* FROM CUSTOMERS C JOIN ORDERS O ON C.CUSTID = O.CUSTID JOIN ITEMS I ON O.ITEMID = I.ITEMID WHERE I.PRICE > 5000;
SELECT CUSTNAME, ADDRESS FROM CUSTOMERS WHERE CUSTID NOT IN (SELECT O.CUSTID FROM ORDERS O JOIN ITEMS I ON O.ITEMID = I.ITEMID WHERE I.ITEMNAME = 'Samsung Galaxy S4');
 LEFT OUTER JOIN
SELECT * FROM CUSTOMERS C LEFT JOIN ORDERS O ON C.CUSTID = O.CUSTID;
 RIGHT OUTER JOIN
SELECT * FROM CUSTOMERS C RIGHT JOIN ORDERS O ON C.CUSTID = O.CUSTID;
SELECT STATE, COUNT(*) AS TOTAL_CUSTOMERS FROM CUSTOMERS GROUP BY STATE;
SELECT CATEGORY, AVG(PRICE) FROM ITEMS GROUP BY CATEGORY HAVING AVG(PRICE) > (SELECT AVG(PRICE) FROM ITEMS);
