-- CREATE TABLE
CREATE TABLE BANK (
    BANKNAME VARCHAR2(50),
    HEADOFFICE VARCHAR2(50),
    BRANCH VARCHAR2(50),
    BRANCHCODE INT
);

-- INSERT INITIAL RECORDS
INSERT INTO BANK VALUES ('SBI','Mumbai','Kochi',101);
INSERT INTO BANK VALUES ('HDFC','Mumbai','Ernakulam',102);
INSERT INTO BANK VALUES ('ICICI','Delhi','Kottayam',103);

-- SAVE CURRENT STATE
SAVEPOINT B1;

-- INSERT MORE RECORDS
INSERT INTO BANK VALUES ('AXIS','Mumbai','Trivandrum',104);
INSERT INTO BANK VALUES ('FEDERAL','Aluva','Muvattupuzha',105);

-- VIEW TABLE
SELECT * FROM BANK;

-- ROLLBACK TO SAVEPOINT (REMOVES LAST TWO INSERTS)
ROLLBACK TO B1;

-- VIEW TABLE AFTER ROLLBACK
SELECT * FROM BANK;

-- COMMIT FINAL DATA
COMMIT;
