-- CREATE TABLE
CREATE TABLE BANK ( BANKNAME VARCHAR2(50), HEADOFFICE VARCHAR2(50), BRANCH VARCHAR2(50), BRANCHCODE INT);

-- INSERT INITIAL RECORDS
INSERT INTO BANK VALUES ('SBI','Mumbai','Kochi',101);
INSERT INTO BANK VALUES ('HDFC','Mumbai','Ernakulam',102);
INSERT INTO BANK VALUES ('ICICI','Delhi','Kottayam',103);
INSERT INTO BANK VALUES ('CNB', 'Punjab', 'Ernakulam', 104);
INSERT INTO BANK VALUES('AXB', 'Kerala', 'Ghaziabad', 105);

--TRUNCATE TABLE BANK;
-- COMMIT FINAL DATA
INSERT INTO BANK VALUES('IFB', 'Tamil Nadu', 'Indirapuram', 106);
COMMIT;
SELECT * FROM BANK;

INSERT INTO BANK VALUES ('AXIS','Mumbai','Trivandrum',107);
-- SAVE CURRENT STATE
SAVEPOINT B1;
INSERT INTO BANK VALUES ('FEDERAL','Aluva','Muvattupuzha',108);
-- SAVE CURRENT STATE
SAVEPOINT B2;

-- ROLLBACK TO SAVEPOINT (REMOVES LAST TWO INSERTS)
ROLLBACK TO B1;

--grant
grant select on BANK to c24csa28;
select * from c24csa28.BANK;
--revoke
revoke select on BANK from c24csa28;

