CREATE TABLE EMP (EMPNO NUMBER(4,0) NOT NULL, ENAME VARCHAR2(20 BYTE), SAL NUMBER(7,2), CONSTRAINT PK_EMP PRIMARY KEY (EMPNO));

--DROP TABLE EMP;

SELECT * FROM EMP;

--rest imported from excel and got bulked data
